services:
  client:
    build: ./client
    restart: always
    ports: 
      - "4000:4000"
    container_name: client
    depends_on:
      - api
  
  api:
    build: ./api
    restart: always
    ports: 
      - "3001:3001"
    container_name: api
    depends_on:
      - nginx
      - db

  nginx:
    build: ./nginx
    restart: always
    container_name: nginx
    ports: 
      - "80:80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    command: ['nginx-debug', '-g', 'daemon off;']
    
  broker:
    build: ./broker
    restart: always
    container_name: broker
    ports:
      - "6379:6379"
    volumes:
      - "brokerdata:/usr/srv/broker/data"
    depends_on:
      - api
      - db

  db:
    build: ./mariadb 
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin
    volumes:
      - "dbdata:/var/lib/mysql"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
 
volumes:
  brokerdata: {}
  dbdata: {}
