networks:
  lbnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16

services:
  client:
    build: ./client
    restart: always
    ports: 
      - "9000:443"
    container_name: client
    env_file:
      - client/.env.prod
    depends_on:
    - auth
    - api
    - steamapi
    - nginx
    - redis
    networks:
      - lbnet
    volumes:
      - "./client/nginx.conf:/etc/nginx/conf.d/default.conf"
      

  auth:
    build: ./auth
    restart: always
    ports: 
      - "4000:443"
    container_name: auth
    env_file:
      - auth/.env.prod
    depends_on:
      - redis
    networks:
      - lbnet
    

  nginx:
    build: ./nginx
    restart: always
    container_name: nginx
    ports: 
      - "443:443"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    command: ['nginx', '-g', 'daemon off;']
    networks:
      - lbnet
  
  api:
    build: ./api
    restart: always
    ports: 
      - "3001:3001"
    container_name: api
    depends_on:
      - nginx
      - redis
    networks:
      - lbnet

  steamapi:
    build: ./steamapi
    restart: always
    ports: 
      - "8000:443"
    env_file:
      - ./steamapi/.env.prod
    container_name: steamapi
    depends_on:
      - api
      - nginx
      - redis
    networks:
      - lbnet
      
  redis:
    build: ./redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - lbnet