services:
  # client:
  #   build: ./client
  #   restart: always
  #   ports: 
  #     - "4000:80"
  #   container_name: client
  #   depends_on:
  #     - api
  
  # api:
  #   build: ./api
  #   restart: always
  #   ports: 
  #     - "3001:3001"
  #   container_name: api
  #   environment:
  #     - CELERY_BROKER_URL=redis://broker:6379/0
  #   depends_on:
  #     - nginx
  #     - db

  # nginx:
  #   build: ./nginx
  #   restart: always
  #   container_name: nginx
  #   environment:
  #     - ENV=dev
  #     - CORS_ENABLED=true
  #   ports: 
  #     - "80:80"
  #   volumes:
  #     - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
  #   command: ['nginx-debug', '-g', 'daemon off;']
    
  broker:
    build: ./redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    # depends_on:
    #   - api
    #   - db

#   db:
#     image: mariadb:latest
#     restart: always
#     container_name: mariadb
#     ports:
#       - "3306:3306"
#     environment:
#       MARIADB_ROOT_PASSWORD: admin
#     volumes:
#       - "dbdata:/var/lib/mysql"
 
# volumes:
#   dbdata: {}
